version: '2.1'
volumes:
  postgres_data:

services:
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGIS_VERSION_TAG=${POSTGIS_VERSION_TAG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DATADIR=${DATADIR}
      - PASSWORD_AUTHENTICATION=${PASSWORD_AUTHENTICATION}
    healthcheck:
      test: "exit 0"

  geoserver:
    image: kartoza/geoserver:2.13.0
    ports:
      - "${GEOSERVER_PORT}:8080"
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ${HOME}:/home/${USER}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  geogig:
    image: kartoza/geogig:1.2.1
    volumes:
      - ./geogig_repo:/geogig_repo/gis
      - ${HOME}:/home/${USER}
      - ./geoserver_data:/opt/geoserver/data_dir
    ports:
      - "${GEOGIG_PORT}:8182"
    environment:
      - GEOGIG_CACHE_MAX_SIZE=${GEOGIG_CACHE_MAX_SIZE}
      - EMAIL=${EMAIL}
      - USER_NAME=${USER_NAME}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT_INTERNAL}
      - PGDATABASE=${PG_GEOGIG_DATABASE}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASS}
      - PGSCHEMA=${PGSCHEMA}
    depends_on:
      db:
        condition: service_healthy
      geoserver:
        condition: service_healthy




