version: '3'

volumes:
   geogig_repo:

services:

   geoserver:
      image: kartoza/geogig:${GEOGIG_VERSION_TAG}
      build:
        context: .
        args:
          VERSION: ${GEOGIG_VERSION_TAG}
          JAVA_HOME: ${JAVA_HOME}
          GEOGIG_URL: ${GEOGIG_URL}
          IMAGE_VERSION: ${GEOGIG_VERSION}
      volumes:
        - geogig_repo:/geogig_repo/gis
      ports:
        - ${GEOGIG_PORT}:8080
      restart: on-failure
      environment:
        - STORAGE_BACKEND=${STORAGE_BACKEND}

