version: '2.1'
volumes:
  postgres_data:

services:
  db:
    image: kartoza/postgis:13-3.1
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "25435:5432"
    env_file:
      - database.env
    healthcheck:
      test: "exit 0"

  geoserver:
    image: kartoza/geoserver:2.13.0
    ports:
      - "8600:8080"
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ${HOME}:/home/${USER}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  geogig:
    image: kartoza/geogig:1.2.1
    volumes:
      - ./geogig_repo:/geogig_repo/gis
      - ${HOME}:/home/${USER}
      - ./geoserver_data:/opt/geoserver/data_dir
    ports:
      - "38080:8182"
    env_file:
      - geogig.env
    depends_on:
      db:
        condition: service_healthy
      geoserver:
        condition: service_healthy




